require 'factory_bot'
include FactoryBot::Syntax::Methods

puts "Destroying old records"

SubCategory.destroy_all
MainCategory.destroy_all

puts "Creating Main Categories that have sub-categories"
transportation_category         = create(:main_category, name: "Transportation")
debt_repayment_category         = create(:main_category, name: "Debt Repayment")
food_and_drinks_category        = create(:main_category, name: "Food & Drinks")
clothing_and_shoes_category     = create(:main_category, name: "Clothing, Shoes & Attire")
education_category              = create(:main_category, name: "Education")
financial_services_category     = create(:main_category, name: "Financial Services Costs & Charges")
gifts_and_donations_category    = create(:main_category, name: "Gifts & Donations")
health_and_wellbeing_category   = create(:main_category, name: "Health & Wellbeing")
holiday_category                = create(:main_category, name: "Holiday Costs")
household_category              = create(:main_category, name: "Household")
insurance_category              = create(:main_category, name: "Insurance")
leisures_and_hobbbies_category  = create(:main_category, name: "Leisures and Hobbies (non-Vacation)")
obligations_category            = create(:main_category, name: "Obligations")
personal_care_category          = create(:main_category, name: "Personal Care")
savings_category                = create(:main_category, name: "Savings")
special_oneoff_category         = create(:main_category, name: "Special/One-off/Unusual Event")
utilities_category              = create(:main_category, name: "Utilities")
children_category               = create(:main_category, name: "Children")

puts "Creating Main Categories without sub-categories"
create(:main_category, name: "ATM Cash withdrawal")
create(:main_category, name: "Voucher Purchase")

puts "Creating all sub-categories"
create(:sub_category, main_category: transportation_category, name: "Accessories/Tools")
create(:sub_category, main_category: transportation_category, name: "Bus/Taxi/Train Fare")
create(:sub_category, main_category: transportation_category, name: "Fuel")
create(:sub_category, main_category: transportation_category, name: "Maintenace/Repairs")
create(:sub_category, main_category: transportation_category, name: "Other")
create(:sub_category, main_category: transportation_category, name: "Parking Fees")
create(:sub_category, main_category: transportation_category, name: "Registration/License")
create(:sub_category, main_category: transportation_category, name: "Vehicle Payments")

create(:sub_category, main_category: debt_repayment_category, name: "Credit Payment")
create(:sub_category, main_category: debt_repayment_category, name: "Acquaintances Payment")
create(:sub_category, main_category: debt_repayment_category, name: "Loan Payment")

create(:sub_category, main_category: food_and_drinks_category, name: "Drinks")
create(:sub_category, main_category: food_and_drinks_category, name: "Lunch/Diner-out")
create(:sub_category, main_category: food_and_drinks_category, name: "Fish/Seafood")
create(:sub_category, main_category: food_and_drinks_category, name: "Friends/Relatives")
create(:sub_category, main_category: food_and_drinks_category, name: "Groceries")
create(:sub_category, main_category: food_and_drinks_category, name: "Infant Food")
create(:sub_category, main_category: food_and_drinks_category, name: "Meat/Poultry")
create(:sub_category, main_category: food_and_drinks_category, name: "Pet Food")
create(:sub_category, main_category: food_and_drinks_category, name: "Snacks")

create(:sub_category, main_category: clothing_and_shoes_category, name: "Alterations costs")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Care Products")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Fabric")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Normal Clothes")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Sewing Costs")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Shoes")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Special Clothes & Costumes")
create(:sub_category, main_category: clothing_and_shoes_category, name: "Underwear")

create(:sub_category, main_category: education_category, name: "Books")
create(:sub_category, main_category: education_category, name: "Lessons/Tutorials")
create(:sub_category, main_category: education_category, name: "Misc Fees")
create(:sub_category, main_category: education_category, name: "School clubs subscriptions")
create(:sub_category, main_category: education_category, name: "School/Field trips")
create(:sub_category, main_category: education_category, name: "Stationary supplies")
create(:sub_category, main_category: education_category, name: "Tuition")

create(:sub_category, main_category: financial_services_category, name: "ATM Fees")
create(:sub_category, main_category: financial_services_category, name: "Credit/Loan Interest")
create(:sub_category, main_category: financial_services_category, name: "Late payment fee")
create(:sub_category, main_category: financial_services_category, name: "Lending money out")
create(:sub_category, main_category: financial_services_category, name: "Overdraft Interest")
create(:sub_category, main_category: financial_services_category, name: "Overdraft Limit charge")
create(:sub_category, main_category: financial_services_category, name: "Service fees")

create(:sub_category, main_category: gifts_and_donations_category, name: "Charitable Donations")
create(:sub_category, main_category: gifts_and_donations_category, name: "Events/Socials Contributions")
create(:sub_category, main_category: gifts_and_donations_category, name: "Family Money Pot Contributions")
create(:sub_category, main_category: gifts_and_donations_category, name: "Gifts/Greeting Cards Given")
create(:sub_category, main_category: gifts_and_donations_category, name: "Help to Family/Friends")
create(:sub_category, main_category: gifts_and_donations_category, name: "Other")
create(:sub_category, main_category: gifts_and_donations_category, name: "Religious Donations")
create(:sub_category, main_category: gifts_and_donations_category, name: "Tips(Gratuities)")
create(:sub_category, main_category: gifts_and_donations_category, name: "Tithes")

create(:sub_category, main_category: health_and_wellbeing_category, name: "Doctor/Specialist Fees")
create(:sub_category, main_category: health_and_wellbeing_category, name: "Hospital & Other Services")
create(:sub_category, main_category: health_and_wellbeing_category, name: "Other")
create(:sub_category, main_category: health_and_wellbeing_category, name: "Veterinarian/Pet Care")
create(:sub_category, main_category: health_and_wellbeing_category, name: "Vitamins & Medications")

create(:sub_category, main_category: holiday_category, name: "Accommodation")
create(:sub_category, main_category: holiday_category, name: "Entertainment/Leisure")
create(:sub_category, main_category: holiday_category, name: "Food, Drinks & Snacks")
create(:sub_category, main_category: holiday_category, name: "Luggage Fees")
create(:sub_category, main_category: holiday_category, name: "Personal Supplies Items")
create(:sub_category, main_category: holiday_category, name: "Transportation")
create(:sub_category, main_category: holiday_category, name: "Trip package")

create(:sub_category, main_category: household_category, name: "Appliances/Tools/Gadgets")
create(:sub_category, main_category: household_category, name: "Bathroom Accessories Supplies")
create(:sub_category, main_category: household_category, name: "Decoration items")
create(:sub_category, main_category: household_category, name: "Furniture")
create(:sub_category, main_category: household_category, name: "House ownership dues")
create(:sub_category, main_category: household_category, name: "Improvements")
create(:sub_category, main_category: household_category, name: "Kitchen Appliances/Tools/Utensils Supplies")
create(:sub_category, main_category: household_category, name: "Maintenance & Repairs costs")
create(:sub_category, main_category: household_category, name: "Products Supplies (Cleaning/Maintenance)")
create(:sub_category, main_category: household_category, name: "Rent/Mortgage payment")

create(:sub_category, main_category: insurance_category, name: "Appliance/Gadget")
create(:sub_category, main_category: insurance_category, name: "Automobile")
create(:sub_category, main_category: insurance_category, name: "Health")
create(:sub_category, main_category: insurance_category, name: "Home/Rental")
create(:sub_category, main_category: insurance_category, name: "Life")

create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Books or Magazines")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Board Games")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Children Toys")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Cinema")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Concerts/Plays/Theatre")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Craft Products/Tools")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Cultural Events(Carnaval, parades, festivals)")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Film or Photo Shooting/Printing")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Gadgets or Tools")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Gym/Sport club Membership/Dues")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Lottery/Raffle tickets")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Outdoor recreation")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Service(Movie/Music/Content/Newspaper) subscription")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Sport Events")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Sporting goods/tools")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Tourist Attractions Fees (parks, museums, zoos,etc)")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Video games")
create(:sub_category, main_category: leisures_and_hobbbies_category, name: "Videos/CDs or DVDs purchase or rental")

create(:sub_category, main_category: obligations_category, name: "State/Local Tax")
create(:sub_category, main_category: obligations_category, name: "Fine/Penalty")
create(:sub_category, main_category: obligations_category, name: "Other")

create(:sub_category, main_category: personal_care_category, name: "Beauty treatment services")
create(:sub_category, main_category: personal_care_category, name: "Cosmetic products or tools")
create(:sub_category, main_category: personal_care_category, name: "Essential toileteries")
create(:sub_category, main_category: personal_care_category, name: "Haircare products")
create(:sub_category, main_category: personal_care_category, name: "Haircare service")
create(:sub_category, main_category: personal_care_category, name: "Manicure/Pedicure tools/products/services")
create(:sub_category, main_category: personal_care_category, name: "Misc Product or Tool")
create(:sub_category, main_category: personal_care_category, name: "Natural multi-purpose products")
create(:sub_category, main_category: personal_care_category, name: "Perfume/cologne/Eau de Toilette")
create(:sub_category, main_category: personal_care_category, name: "Pet Care supplies")

create(:sub_category, main_category: savings_category, name: "Education")
create(:sub_category, main_category: savings_category, name: "Investments")
create(:sub_category, main_category: savings_category, name: "Other")
create(:sub_category, main_category: savings_category, name: "Retirement")
create(:sub_category, main_category: savings_category, name: "Travel/Leisure")

create(:sub_category, main_category: special_oneoff_category, name: "Catering Services")
create(:sub_category, main_category: special_oneoff_category, name: "Driving License")
create(:sub_category, main_category: special_oneoff_category, name: "Event Food Supplies")
create(:sub_category, main_category: special_oneoff_category, name: "Home move/purchase related fees")
create(:sub_category, main_category: special_oneoff_category, name: "Party supplies(disposables/decorations)")
create(:sub_category, main_category: special_oneoff_category, name: "Passport Application")
create(:sub_category, main_category: special_oneoff_category, name: "Postage-related/Delivery fees")
create(:sub_category, main_category: special_oneoff_category, name: "State Service Application fees")
create(:sub_category, main_category: special_oneoff_category, name: "Visa Application")

create(:sub_category, main_category: utilities_category, name: "Garbage and Recycling")
create(:sub_category, main_category: utilities_category, name: "Home Phone bills")
create(:sub_category, main_category: utilities_category, name: "Internet Service")
create(:sub_category, main_category: utilities_category, name: "Line Rental")
create(:sub_category, main_category: utilities_category, name: "Mobile Phone bills")
create(:sub_category, main_category: utilities_category, name: "Television (Cable&Satellite)")
create(:sub_category, main_category: utilities_category, name: "Water/Sewer")

create(:sub_category, main_category: children_category, name: "Bedding or Nursery")
create(:sub_category, main_category: children_category, name: "Books")
create(:sub_category, main_category: children_category, name: "Clothes/Shoes/Headpieces")
create(:sub_category, main_category: children_category, name: "Education")
create(:sub_category, main_category: children_category, name: "Furniture/Useful Appliance or Tool")
create(:sub_category, main_category: children_category, name: "Health, Safety or Wellbeing")
create(:sub_category, main_category: children_category, name: "Leisure")
create(:sub_category, main_category: children_category, name: "Lessons")
create(:sub_category, main_category: children_category, name: "Nursery/Daycare Fees")
create(:sub_category, main_category: children_category, name: "Personal Care")
create(:sub_category, main_category: children_category, name: "Special Clothes or Uniform")
create(:sub_category, main_category: children_category, name: "Toys or Playtime")
